# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "furome"
client_id = "856f6c386e8c2ad7e66cc0097748cf2a"
application_url = "https://fee-precisely-qualifications-modes.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fee-precisely-qualifications-modes.trycloudflare.com/auth/callback",
  "https://fee-precisely-qualifications-modes.trycloudflare.com/auth/shopify/callback",
  "https://fee-precisely-qualifications-modes.trycloudflare.com/api/auth/callback",
  "https://fee-precisely-qualifications-modes.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "strandhealth.myshopify.com"
